pipeline {

    agent any

    environment {
        APP = "gatevise"
        IMAGE = "gatevise"
    }

    stages {

        stage('Clone') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('GateSecuritySystem') {
                    sh 'docker build -t ${IMAGE} .'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                docker stop ${APP} || true
                docker rm ${APP} || true

                docker run -d \
                  --name ${APP} \
                  --network gatevise-net \
                  -e DB_HOST=gatevise-mysql \
                  -e DB_USER=root \
                  -e DB_PASSWORD=9923 \
                  -e DB_NAME=db \
                  -p 5000:5000 \
                  ${IMAGE}
                '''
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful'
        }

        failure {
            echo 'Deployment Failed'
        }
    }
}
